datastore:
  filename: /data/health_status.json

scheduler:
  period_sec: 5

services:
  receiver:
    url: http://receiver:8080/health
  storage:
    url: http://storage:8090/health
  processing:
    url: http://processing:8100/health
  analyzer:
    url: http://analyzer:8110/health